- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
Adds a .travis.yml that should install and run `mdl`. Note that the `generic` image on Travis CI should have Ruby preinstalled.
Closes #19.
> Add .travis.yml

- .hooks/README.md
- .hooks/pre-commit
Adds a pre-commit hook to run `mdl .` before allowing commits. These can't be enforced (hence we still should use Travis) but I'm quite fond of them.
> Add pre-commit hook

- README.md
n/a
Adds a link to the new Ideas repo, and some formatting adjustments to the `Other Repos` section
> Add link to Ideas repo

- handbook/README.md
- handbook/project-management/sprints.md
n/a
This PR brings documentation regarding sprint management at Launch Pad more inline with how things currently work, and reduces some of the fancy stuff that used to be there (e.g. epics and usage of the word "scrum")
Co-authored with @srijonsaha 
Preview: https://deploy-preview-64--ubclaunchpad-docs.netlify.app/handbook/project-management/sprints
> refresh sprint documentation

- .vuepress/config.js
- package.json
similar to https://github.com/ubclaunchpad/ubclaunchpad.com/pull/170 - similarly, no existing package exists so I made [`@ubclaunchpad/vuepress-plugin-fathom`](https://github.com/ubclaunchpad/vuepress-plugin-fathom)
see the dashboard here: https://app.usefathom.com/share/oemmhhle/docs.ubclaunchpad.com
since this is just for tracking page views, thinking of getting rid of google analytics and using fathom instead
> add fathom analytics

- handbook/onboarding/strategy.md
Closes #79
* improve formatting with headers
* clarify strategy github sponsorship issues and remove link to the sponsorship spreadsheet (since I think the issues will take precedence?)
* events: add timeline to issue template (the template includes the full checklist 😄 )
https://deploy-preview-80--ubclaunchpad-docs.netlify.app/handbook/onboarding/strategy#workflows
> strategy onboarding tidy-up

- .vuepress/config.js
- CONTRIBUTING.md
- package.json
n/a
makes header links much easier to deal with by stripping out leading unicode emoji
e.g. https://deploy-preview-86--ubclaunchpad-docs.netlify.app/handbook/#onboarding
> strip leading emoji from header anchors

- handbook/onboarding/design.md
- handbook/onboarding/everyone.md
- handbook/onboarding/leads.md
- handbook/onboarding/strategy.md
- handbook/project-management/sprints.md
n/a
Adds a bunch of links to help make the onboarding section more useful.
Most notably, the Leads onboarding should have the specific links and setup that we want everyone to look at during the upcoming Leads kickoff meeting
I've also added some more aggressive hints to read the GitHub and Slack guides 🙃 
https://deploy-preview-83--ubclaunchpad-docs.netlify.app/handbook/onboarding/leads
> add more links to workflows

- handbook/manifesto.md
follow-up to #87 
* add back our old software engineering section because i still like the quote :))) sorry
* condensed current "what we offer / what we need" sections into a targeted "for sponsors" section
https://deploy-preview-90--ubclaunchpad-docs.netlify.app/handbook/manifesto
> adjust manifesto and add software engineering section

- .vuepress/config.js
- package.json
n/a
This allows us to dodge adblockers since nobody knows of the ubclauncpad.com domain. Neat fathom feature https://usefathom.com/support/custom-domains
blocked by https://github.com/unstacked/fathom-client/issues/5
> add custom fathomURL

- .github/PULL_REQUEST_TEMPLATE.md
- .vuepress/config.js
- CONTRIBUTING.md
- handbook/onboarding/design.md
- handbook/onboarding/leads.md
- handbook/onboarding/strategy.md
- handbook/tools/deployment.md
- handbook/tools/slack.md
- package-lock.json
- package.json
n/a
Finally possible now that my PR at https://github.com/vuejs/vuepress/pull/2380 is merged 😅 
This PR defines sidebars for related groups of pages (ie `/handbook/onboarding/...`). Unfortunately must be manually defined.
Hopefully, this helps with navigation - examples:
> define sidebar groups for related pages

- .vuepress/config.js
- handbook/README.md
- handbook/tools/analytics.md
Closes #65 related: https://github.com/ubclaunchpad/ubclaunchpad.com/pull/178
Adds Fathom Analytics as our recommended web analytics solution, and provides a quick guide and examples to get started.
Preview: https://deploy-preview-105--ubclaunchpad-docs.netlify.app/handbook/tools/analytics
> add Fathom Analytics guidance

- handbook/project-management/sprints.md
n/a
* Adding example of pre meeting/standup document (inspired by @MLH-Fellowship)
> Add example for prep doc

- resources/groundwork/web.md
Closes #128 
Document sync stack (stuff on Redis not finished). @srijonsaha edit/change as you please :D
> Sync stack description

- handbook/tools/deployment.md
- resources/deployment.md
fixes #110 
I took it because... aaah saw it and was like "This should be quick"
Adds simple Heroku documentation. Mostly just references the Heroku docs. The duplication of deployment documentation feels off, but I guess one is for general documentation and another for Launch Pad specific options? Still not sure why both need to exist so opinions are welcome! (thinking best thing to do maybe is just referencing the `handbook` one from the `resources` one)
> Adds heroku documentation

- handbook/recruitment/designer.md
- handbook/recruitment/developer.md
n/a
Previously, these pages had a warning saying that we are not accepting applications. However, with the upcoming recruitment campaign, we want to say that we are now accepting applications and we want to link users directly to the application form.
> add tips linking to google recruitment forms

- .vuepress/config.js
- handbook/README.md
- handbook/onboarding/leads.md
- handbook/tools/drive.md
n/a
I'm working on documenting our recruitment process, and since we leverage Drive heavily for this, this PR sets up a page to consolidate this information
> consolidate google drive info in drive.md

- handbook/project-management/scope.md
- handbook/strategy/recurring-processes.md
n/a
Applies some changes from our kickoff retrospective today:
* Tweaks to icebreaker format (mostly just a link to https://github.com/ubclaunchpad/docs/issues/186 though)
* Changes to ideation format - added recommendation for more rounds
* Response to feedback that kickoff was unexpectedly long with warning that these things are long
* Add advice about "risky ideas", to help leads steer discussions
* Add note in ideation discussion about ideas/people dominating the conversation
> kickoff retrospective: icebreaker and ideation changes, risky ideas advice

- handbook/recruitment/designer.md
- handbook/recruitment/developer.md
* Removed warning that we're not accepting applications for developers and designers (I chose not to uncomment the "we're currently accepting applications" tip because we're definitely going to forget to remove that, and I think it's very unlikely that a prospective member gets here without first seeing the application section on our website)
* Updated the time commitment to reflect our hybrid meeting model
> Update role descriptions

- .github/workflows/sync.yml
Current sync cronjob will create infinite stale branches for every synchronization PR. But with this change, it will only create one PR and use up the same one branch every day.
> Prevent creation of stale branches in s3-sync cronjob
