Exploration/README.md
README.md

Create exploration section, add OSTEP and Crafting Interpreters.

Create Exploration section

---

GettingStarted/Tools.md

Related to https://github.com/ubclaunchpad/strategy/issues/17
Add gitkraken as tool recommendation

Add gitkraken as tool recommendation

---

README.md

Closes #25
Adds links to non-code Launch Pad repos to README

Add links to other Launch Pad repos to README

---

GettingStarted/Resources.md

Closes #0
Added every-programmer-should-know to resources

Added every-programmer-should-know to resources

---

Exploration/README.md

Adds coding practice section to `Exploration`, containing Project Euler and LeetCode for now.

Add coding practice section to Exploration

---

Exploration/README.md

Add Systems Design Primer and a new distributed systems section to Exploration

Add systems design primer

---

.vscode/settings.json
DevelopmentBible/GitWorkflow.md
DevelopmentBible/RepositoryManagement.md
DevelopmentBible/Requirements.md
DevelopmentBible/SprintPlanning.md
Exploration/README.md
GettingStarted/Administrivia.md
GettingStarted/Languages.md
GettingStarted/README.md
GettingStarted/Resources.md
GettingStarted/Tools.md
GettingStarted/x/README.md
GettingStarted/x/Windows.md

for #7 
* Added TOC to a bunch of pages
* Added @ginsstaahh 's Windows Dual-Booting guide
* Added featured slack channels
* Added a new page, `Languages`, for language-specific resources
* Added Go resources

Featured channels, windows dual-booting, languages, and TOCs

---

resources/tools/slack.md

Closes https://github.com/ubclaunchpad/ideas/issues/13
*Briefly describe the changes you made*
Document the new Slack channel naming scheme (all channels in Slack have been updated already) and add more featured channels

Document Slack naming scheme

---

README.md

https://github.com/ubclaunchpad/ideas/issues/15

Adds Alumni Entry

---

README.md

*List relevant tickets, e.g. 'Closes #<some_ticket_number>'*
n/a
*Briefly describe the changes you made*
add link to ubclaunchpad.com repository and what is contained there

add link to ubclaunchpad.com repository

---

resources/README.md

add link to ubclaunchpad.com as a Vue resource

---

project-management/repositories.md
resources/languages.md

add ts/js resources, update CI recommendation 

---

resources/README.md
resources/windows.md

Closes #38 
- add WSL 2 guide
- fix broken README link

Add WSL guide

---

.vuepress/config.js
package.json

until an official dark theme gets merged, this looks pretty good imo (https://github.com/vuejs/vuepress/pull/2301)

add a theme that allows dark mode

---

.vuepress/config.js
handbook/README.md

Now you can always see what part of the site you are in

fix navbar, some links

---

.vuepress/config.js
handbook/README.md
index.md
introduction.md
netlify.toml

*List relevant tickets, e.g. 'Closes #<some_ticket_number>'*
Closes #58 
*Briefly describe the changes you made*
add netlify header rules declaring `/page` to be HTML
e.g. 
* https://deploy-preview-59--ubclaunchpad-docs.netlify.app/CONTRIBUTING 
* https://deploy-preview-59--ubclaunchpad-docs.netlify.app/resources/git-workflow

fix broken clean urls

---

handbook/tools/slack.md

*List relevant tickets, e.g. 'Closes #<some_ticket_number>'*
Closes #61
*Briefly describe the changes you made*
Add slightly newer documentation on the new Rocket 2 system.

Add rocket 2 doc updates

---

handbook/README.md
handbook/tools/github.md
introduction.md

n/a
I'll be working on some more handbook stuff soon, this PR condenses the handbook README to be more like the `/resources` README

adjust handbook README to be more condensed

---

handbook/README.md
handbook/onboarding.md
handbook/onboarding/design.md
handbook/onboarding/everyone.md
handbook/onboarding/strategy.md
handbook/onboarding/tech-leads.md
handbook/project-management/sprints.md

n/a
blocked by #64 
set up onboarding pages

init onboarding pages

---

handbook/project-management/scope.md

n/a
refresh the scope section to better capture:
* time limitations
* trimming down MVP definition to "single core feature"
* new timeline proposal
preview: https://deploy-preview-69--ubclaunchpad-docs.netlify.app/handbook/project-management/scope

new scope guidance

---

handbook/project-management/scope.md

n/a
wording per meeting with @sandyklc , @renehuang1999 
preview: https://deploy-preview-71--ubclaunchpad-docs.netlify.app/handbook/project-management/scope#project-timeline

update project timeline

---

.vscode/extensions.json
.vscode/settings.json

n/a
adds vscode recommendations and tab settings

add vscode settings and recommendations

---

handbook/tools/github.md

n/a
adds more details to the pull requests pros, and links to @sourcegraph's explanation

flesh out pull requests pros

---

handbook/onboarding/strategy.md

follow-up to #80 
* note that events stuff is all in the issue template

move strategy events timeline to issue template

---

.vuepress/config.js
handbook/README.md

n/a
add quick links in dropdown for a variety of useful things

add quick links dropdown in navbar

---

handbook/manifesto.md

Update vision and subtitles
Closes #75

update manifesto: vision

---

handbook/onboarding/everyone.md
index.md

n/a
Followups to the other day's meeting:
* add text to promote search
* emphasize setting up notifications in onboarding

search text, emphasize github notifications

---

handbook/onboarding/design.md

Updated Figma onboarding, how designers will use Github (with links to github guide) and linking drive assets to Github for easy asset management.
Closes #89

updated design onboarding

---

.gitignore
package-lock.json
package.json

Closes #
Netlify caches things weirdly without package-lock.json, which means sometimes updating a dependency requires manually clearing the build cache via the netlify UI.

add package-lock.json, pin dependencies

---

.github/CODEOWNERS

n/a
automatically tag @ubclaunchpad/design , @ubclaunchpad/strategy as reviewers on certain pages

add design, strategy as codeowners of specific sections

---

index.md

n/a
add to the search tips section on the homepage

add more search tips

---

handbook/onboarding/design.md

n/a
adds rules for how to make sure we don't lose access to Drive and Figma design assets

add rules for sharing Drive and Figma things

---

.vuepress/fulltextSearchFunctions.js

n/a
Often find myself just looking for a specific repo - this adds a search shortcut for that

add repo search suggestion

---

handbook/onboarding/design.md
handbook/onboarding/everyone.md
handbook/onboarding/leads.md
handbook/onboarding/strategy.md

n/a
Removes full "docs.ubclaunchpad.com" links and replaces them with relative links

use relative links instead of full links

---

handbook/manifesto.md

n/a
For context: this is a very old code of conduct written way back in the day. This PR updates it to:
* remove references to specific meetings and time commitment
* remove some hard requirements (e.g. completing tickets)
* clarify what we want members to participate in as far as discussions go (follow-up to [slack thread](https://ubclaunchpad.slack.com/archives/G013BC5RC22/p1592096055035800?thread_ts=1592068514.033700&cid=G013BC5RC22))

refresh code of conduct

---

.hooks/README.md
.hooks/pre-commit
package.json

n/a
To try and encourage edits, we also recommend editing pages directly on GitHub (https://docs.ubclaunchpad.com/CONTRIBUTING#the-easy-way), so it makes this slightly redundant. It was also out of date - at this point, might as well remove it and rely on CI + `npm run lint`

remove hooks

---

.vuepress/config.js
handbook/README.md
handbook/tools/social-media.md

for #109 
Creates a new `social-media` page, and sets up some sections. Once this is merged, @sandyklc will add some more details!
Preview: https://deploy-preview-112--ubclaunchpad-docs.netlify.app/handbook/tools/social-media

create social-media page

---

handbook/tools/deployment.md

Closes #49 
Document the sponsored OSS account, the requirements, and tips on Netlify configuration. Some details: #49, https://github.com/ubclaunchpad/strategy/issues/51
Add brief mention of Inertia, and set up Heroku section for #110 
Preview: https://deploy-preview-111--ubclaunchpad-docs.netlify.app/handbook/tools/deployment

add netlify and inertia deployment options

---

.vuepress/config.js
CONTRIBUTING.md
README.md
package-lock.json
package.json

similar to https://github.com/ubclaunchpad/ubclaunchpad.com/pull/182
* Remove Google Analytics
* Improve documentation about Fathom in docs.ubclaunchpad.com
* add badge for current visitors

remove google analytics, document fathom a bit better

---

handbook/recruitment/design-lead.md
handbook/recruitment/tech-lead.md

add notice that we are not currently accepting applications

---

.vuepress/config.js
resources/README.md
resources/groundwork/android.md
resources/groundwork/ios.md
resources/groundwork/web.md

n/a
Sets up pages for getting groundwork started

create project groundwork section

---

handbook/README.md
handbook/recruitment/overview.md

n/a
From our discussions today at https://docs.google.com/document/d/19s4uR2fh6816SDLpoMIwR1eHXv89JogAYgWvAAHfFis/edit#
Preview: https://deploy-preview-121--ubclaunchpad-docs.netlify.app/handbook/recruitment/overview

document our experience buckets

---

handbook/tools/social-media.md

n/a
Try it here: https://deploy-preview-126--ubclaunchpad-docs.netlify.app/handbook/tools/social-media#accounts
Before:
After:

improve link to social accounts

---

.vuepress/config.js
resources/README.md
resources/groundwork/stack-choosing.md

n/a
Based on today's meeting at https://docs.google.com/document/d/1ZyX8MtEF7v_ka6EvxtyrTnYZv_0YCwVAyygOQmzARYY/edit

add stack-choosing guidance

---

.markdownlint.json
resources/groundwork/web.md

n/a
set up stacks reference layout and add rob's stack - see https://docs.google.com/document/d/1ZyX8MtEF7v_ka6EvxtyrTnYZv_0YCwVAyygOQmzARYY/edit

set up web stacks section with rob's stack

---

.github/workflows/checks.yml
.spelling
handbook/onboarding/design.md
handbook/onboarding/leads.md
handbook/onboarding/strategy.md
package.json

n/a
Fixes some spelling errors surfaced by the spellchecker in #120 - thanks @srijonsaha !
Also enables chalk colouring - looks like we just have to forcibly enable it, as `mdspell` depends on `chalk`, and `chalk` probably disables color in CI by default because there was a PR "recently" to enable it in Actions (https://github.com/chalk/supports-color/pull/102)

fix some spelling errors

---

handbook/README.md

n/a
Document our mission with the handbook. Preview: https://deploy-preview-130--ubclaunchpad-docs.netlify.app/handbook/
Hopefully get across that:
* it feels bad to have no idea what is going on - written processes remove the "tribal knowledge" aspect of getting things done, and hopefully allows more people to participate in what we do
* we waste a lot of time trying to figure out what previous years have done, rather than focusing on improving

add section on why we have a handbook

---

resources/groundwork/web.md

Closes #127 
Add documentation for MERN stack as per https://docs.google.com/document/d/1ZyX8MtEF7v_ka6EvxtyrTnYZv_0YCwVAyygOQmzARYY/edit

Add documentation for MERN stack

---

resources/groundwork/web.md

n/a
Web groundwork stuff is good to go :) 

remove work-in-progress notice

---

handbook/README.md

n/a
Adds a goal that @renehuang1999 wrote in https://docs.google.com/document/d/1poh6KvkHMmhqYMkG2IDXiUfmW-AxJRzv5ow7biY-Zs8/edit?usp=sharing that I like :)

add sharing culture to handbook goals

---

handbook/project-management/sprints.md

n/a
For consistency, link to out GitHub guide from sprint planning

add link to github guide about issues

---

.vuepress/config.js
handbook/README.md
handbook/onboarding/leads.md
handbook/onboarding/strategy.md
handbook/tools/email.md

for https://github.com/ubclaunchpad/exec/issues/108, https://github.com/ubclaunchpad/exec/issues/111 , https://github.com/ubclaunchpad/exec/pull/112
Accounts are hard. This tries to set up a bit of a policy around email accounts in response to above issues

add email documentation and policies

---

handbook/manifesto.md

n/a
@frostyshadows noted that our code of conduct wording regarding respect could be stronger, which I do think we need.
As a whole, this whole section probably needs some rethinking, but this is a stopgap that I think is a good amendment

add stronger wording regarding respect in CoC

---

.github/CODEOWNERS
handbook/README.md
handbook/manifesto.md
handbook/strategy/objectives.md
handbook/strategy/sponsors-and-partners.md

n/a
Documents our objectives from https://docs.google.com/presentation/d/1FbCFTzm1Cu5K3vMDm-nHk1az01Bcv7JNdn6tpGJTZ_w/edit#slide=id.g7829d3c0f0_0_44, and gives strategy its own section

add strategy sections and objectives

---

handbook/manifesto.md

Closes #140 
* add co-presidents, leadership, design lead to club structure
* add links to onboarding for more deets

add co-presidents, leadership, design lead to club structure

---

.spelling
resources/languages.md

Relates to #7 
Saw that Go had an entry here and I couldn't let myself live with Rust not being included 😛

Adds Rust resources

---

handbook/README.md
handbook/manifesto.md
handbook/onboarding/leads.md
handbook/onboarding/strategy.md
handbook/recruitment/design-lead.md
handbook/recruitment/tech-lead.md
handbook/strategy/objectives.md
handbook/strategy/recurring-processes.md
handbook/strategy/sponsors-and-partners.md

Closes #150, closes #146 
* Add leadership selection (rough outline)
* Add objectives evaluation (rough outline)
* Add more links
I'm hoping each of these get fleshed out more in the future once we've gone through the processes more, but this should be an okay start :)

document leadership selection, objectives evaluation

---

handbook/recruitment/overview.md

Let me know what you guys think, still giving this a little bit of thought so might make a few changes.
Closes #

Updated Design recruitment goals

---

handbook/recruitment/designer.md
handbook/recruitment/developer.md

companion: https://github.com/ubclaunchpad/ubclaunchpad.com/pull/196
Remove links to applications

remove links to applications

---

handbook/README.md

n/a
Makes the more relevant sections a bit easier to get to

move other repositories to bottom of handbook home

---

handbook/tools/slack.md

n/a
Recommend against using DMs

add note about slack direct messages

---

handbook/recruitment/overview.md

n/a
Questions regarding recruitment decisions have come up, which raises the question of "can we provide feedback?"
I outlined a [rough rationale for this in #tm-leads-2020](https://ubclaunchpad.slack.com/archives/G013BC5RC22/p1599151106004100?thread_ts=1599150920.000600&cid=G013BC5RC22), but I'm not sure if we want to go in-depth about the rationale in this section, since I don't have particularly well-formed thoughts on this.

add feedback policy for recruitment

---

handbook/recruitment/overview.md

n/a
Add a note about total club size.

add note about total members

---

handbook/recruitment/overview.md

n/a
* Add FAQ sections for referrals and decisions
* Add a section on leveraging feedback and decisions to improve our process

add recruitment faq and improvements

---

handbook/strategy/recurring-processes.md

n/a
Publish outline of our [kickoff event](https://docs.google.com/document/d/1LNAiqT0doQrYolgDGlKzO7VwHYUHpf9aGclKdyxfn4k/edit)
[Rendered version](https://deploy-preview-168--ubclaunchpad-docs.netlify.app/handbook/strategy/recurring-processes#kickoff-event)

outline kickoff event as recurring process

---

.vuepress/config.js
.vuepress/public/scrollToAnchorHack.js

n/a
Anchor links don't work consistently in some environments, ie https://docs.ubclaunchpad.com/handbook/strategy/recurring-processes#kickoff-event doesn't scroll me down. This PR adds a hack to make sure it does.

add a dumb hack to make anchor links work consistently

---

index.md
package-lock.json
package.json

Closes #171 
Implemented via a change to my fork of the search plugin we use - see https://github.com/leo-buneev/vuepress-plugin-fulltext-search/pull/10/commits/6b7c8b63cc80cda1b094013dff9627f48211c8d1
This enables usage of docs.ubclaunchpad.com as a custom search engine in various browsers and tools like Alfred

add support for query URL

---

handbook/onboarding/everyone.md

n/a
Profile pictures and full names!

add slack profile picture as onboarding step

---

handbook/onboarding/everyone.md

for https://github.com/ubclaunchpad/rocket2/pull/484

add email to rocket setup

---

handbook/onboarding/design.md
handbook/onboarding/everyone.md
handbook/onboarding/leads.md
handbook/onboarding/strategy.md
handbook/tools/drive.md

n/a
Pending https://github.com/ubclaunchpad/rocket2/pull/484, both our sharing tasks should _only_ be handled by Rocket.

note that github, drive access should only be done through rocket

---

handbook/project-management/scope.md
handbook/strategy/recurring-processes.md

add more ideation advice

---

handbook/project-management/scope.md

add more ideation discussion tips

---

handbook/onboarding/everyone.md

correcting typo

---

CONTRIBUTING.md

Closes #n/a
"More details... is" -> "More details... are" ("details" is plural)
* I've read the [Structuring Content](https://docs.ubclaunchpad.com/CONTRIBUTING#structuring-content) guide - YES
* I've read up on our [Pull Request checks](https://docs.ubclaunchpad.com/CONTRIBUTING#checks) - YES

Correcting grammar

---

handbook/onboarding/everyone.md
handbook/tools/slack.md

Angle brackets cause more confusion than bash variables
ubclaunchpad/rocket2#502
Replace angle brackets with dollar signs

docs: alleviate confusion with bash vars

---

handbook/strategy/recurring-processes.md

n/a
Clarifies some confusing wording about our ideation groups

clarify that the goal of ideation groups is to form teams

---

handbook/onboarding/leads.md

n/a
Documents next steps for when teams are formed! 
Rendered: https://deploy-preview-183--ubclaunchpad-docs.netlify.app/handbook/onboarding/leads#projects-and-teams

add team-starting steps

---

handbook/onboarding/leads.md

n/a
From https://docs.google.com/document/d/1k2WorI7Nyr_u6aWXiZvOBa8-I6tufVzvl7uQ_BRxjmE/edit#

document leads meetings

---

handbook/onboarding/leads.md

n/a
From our leads discussions today at https://docs.google.com/document/d/1k2WorI7Nyr_u6aWXiZvOBa8-I6tufVzvl7uQ_BRxjmE/edit#

add 1-1 recommendations for leads

---

handbook/onboarding/leads.md

n/a
We're not strictly limiting everyone to, for example, Drive for managing docs, but there are advantages to a strong recommendation for a small set of non-technical tooling
Rendered: https://deploy-preview-188--ubclaunchpad-docs.netlify.app/handbook/onboarding/leads#team-tools

document team tools recommendations

---

handbook/onboarding/leads.md

Closes #
This allows people to start making commits

add note to initialize git repository

---

handbook/project-management/scope.md

I looked over the design scope again and I don't think I'm going to make many changes since it still seems like we're on track. (we are on week 1 and teams should finalize their features by next week by the UX workshop and they will start prototyping then) I have it so that by the 3-4th week designs are completely finished for devs to start implementing designs by week 4-5. Let me know if this still a stretch of time and I can shorten it even more but that might be too little time for designers. (I'm just taking note that they only give 5 hrs a week so it's really not a lot of time)
Closes #
* I've read up on our [Pull Request …

Edited Design Scope

---

handbook/strategy/recurring-processes.md

narrrowed -> narrowed
specc'd -> spec'd (while informal, "spec'd" or "specced" seems to be the accurate way to spell this word) -- forgot to implement this patch
leadership -> Leadership -- for consistency, as we've capitalized both "leadership" and "strategy" when referring to the teams throughout the article
Affects #193
* I've read the [Structuring Content](https://docs.ubclaunchpad.com/CONTRIBUTING#structuring-content) guide - YES
* I've read up on our [Pull Request checks](https://docs.ubclaunchpad.com/CONTRIBUTING#checks) - YES

Correcting typos, capitalizing team names

---

handbook/README.md
handbook/design/branding.md

Creates a design section, and add some branding guidelines to start off based on #193 recommendations.
Closes https://github.com/ubclaunchpad/docs/issues/193 , affects https://github.com/ubclaunchpad/docs/issues/107

create design section, add basic branding

---

.spelling
handbook/project-management/repositories.md

Reorganize and refresh advice on repository management, covering topics like code tooling, testing, and CI/CD
Rendered: https://deploy-preview-199--ubclaunchpad-docs.netlify.app/handbook/project-management/repositories
Closes #98 

refresh repository management page

---

handbook/tools/slack.md

add #thanks, #announcements as only exceptions to slack naming

---

handbook/onboarding/leads.md
handbook/onboarding/strategy.md

Aligns with https://github.com/ubclaunchpad/exec/pull/114

tweak instructions for exec

---

handbook/tools/social-media.md

add disclaimer that social media guidance is not perfect

---

handbook/onboarding/leads.md

add guidance on continuing projects

---

handbook/onboarding/leads.md
handbook/recruitment/design-lead.md
handbook/recruitment/designer.md
handbook/recruitment/developer.md
handbook/recruitment/strategy.md
handbook/recruitment/tech-lead.md
handbook/strategy/recurring-processes.md

update tech lead role page

---

.spelling
handbook/tools/deployment.md

Not too much detail here because once you are in the Google Admin console managing the domain is pretty self-explanatory - just wanted to note that we can do this
closes https://github.com/ubclaunchpad/docs/issues/66

add domains guidance

---

handbook/recruitment/tech-lead.md

Add a brief outline of what a tech lead's time commitment looks like
n/a

add brief outline of a tech lead's time commitments

---

handbook/onboarding/everyone.md
handbook/onboarding/leads.md

Remove the dollar signs in the instructions for Rocket setup and provide examples of the Rocket commands

Clarify rocket docs

---

src/docs/recruitment/overview.md
src/docs/recruitment/strategy.md

Fixed minor doc issues

---

.spelling
src/docs/onboarding/tech-lead.md
src/docs/recruitment/tech-lead.md

Specifically:
- Onboarding
- Recruiting

Clean up and update tech lead related documentation

---

src/docs/index.md
src/lib/components/blocks/DocumentStatus.svelte
src/lib/components/blocks/TopBanner.svelte
src/lib/components/layouts/DirectoryNavigation.svelte
src/lib/components/layouts/FullPage.svelte
src/lib/components/layouts/SectionNavigation.svelte
src/routes/+layout.svelte
src/routes/docs/+page.svelte
src/routes/docs/[...slug]/+page.svelte
src/routes/markdown.scss

- sidebar on mobile fix
- folders are by default collapsed
- misc layouts + a component for top banners in the future, e.g. recruitment and other news.

sidebar and layout fixes

---

src/app/globals.css
src/app/page.tsx
src/components/general/faqSection.tsx
src/components/general/footerSection.tsx
src/components/general/navbar.tsx

These are really minor so we can ignore them if they're not that important.
1. I thought we could make the logo on the navbar and footer clickable so that it just redirects the user to the existing landing page
2. Currently if we hover around the join us button and the text itself, the cursor remains as default but only when we move outside the text, the cursor changes into a hand. This change makes it so that anywhere the cursor is hovered on the button changes it into "a hand", rather than a pointer.
3. Apply smooth scroll for the navbar elements, and a hover state with colour when a navbar element is hovered

Minor tweaks and improvements

---

src/app/globals.css
src/components/general/faqSection.tsx

- Fixes an issue where the text of the frequently asked questions title was cut off a bit when clicked from the nav. 
- Added a border around the faq cards.

Faq border redesign + fix scroll issue

---

pnpm-lock.yaml
public/icons/burger-menu.svg
public/icons/cancel.svg
src/app/page.tsx
src/app/portal/admin/forms/[id]/submissions/columns.tsx
src/app/portal/admin/forms/[id]/submissions/data-table.tsx
src/components/general/faqSection.tsx
src/components/general/navbar.tsx
src/components/layouts/navbar.tsx

- Provides a hamburger option for the navbar for users on mobile
- The navbar has a smooth fading transition that will disappear when scrolling down, but reappear when scrolling up
- Fixed some alignment issues with the text of the "frequently asked question" title on mobile

Add hamburger option for mobile navbar

---

src/app/page.tsx
src/components/layouts/navbar.tsx

- Fix error where despite navbar disappearing after scrolling down, can still click buttons
- Make visual change with website hero section with navbar so it could have more space
Previous: 
New:

Fix scroll error with navbar and change spacing for top
